# Generated by Django 3.2.5 on 2021-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengiriman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengiriman',
            name='alamat',
            field=models.TextField(default='-'),
        ),
    ]
